version: '3'

services:
  file_db:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ant
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=service_files
    ports:
      - 5425:5432


  file_migration:
    build: ./
    depends_on:
      - file_db
    environment:
      - LOG_LEVEL=debug
      - DO_MIGRATION=true
      - DATABASE_URL=postgres://ant:secret@file_db:5432/service_files?sslmode=disable
    restart: on-failure
