
services:
  files_datastore:
    hostname: files_datastore
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_USER: ant
      POSTGRES_DB: service_files
      RUST_BACKTRACE: "1"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ant -d service_files" ]
      interval: 2s
      timeout: 3s
      retries: 3
    ports:
      - "5434:5432"


  files_migration:
    build: ./
    depends_on:
      - files_datastore
    environment:
      - LOG_LEVEL=debug
      - DO_MIGRATION=true
      - DATABASE_URL=postgres://ant:s3cr3t@files_datastore:5432/service_files?sslmode=disable
    restart: on-failure
