/*
 * Ant Investor Files
 *
 * An openAPI 3.0 specification that defines how files are stored and accessed on ant investor products
 *
 * API version: 1.0.0
 * Contact: info@antinvestor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"os"
)



// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request, 
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	AddFile(http.ResponseWriter, *http.Request)
	DeleteFile(http.ResponseWriter, *http.Request)
	FindFileById(http.ResponseWriter, *http.Request)
	FindFiles(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	AddFile(context.Context, string, string, bool, string, *os.File) (ImplResponse, error)
	DeleteFile(context.Context, string) (ImplResponse, error)
	FindFileById(context.Context, string) (ImplResponse, error)
	FindFiles(context.Context, string, string, int32, int32) (ImplResponse, error)
}
