/*
 * Ant Investor Files
 *
 * An openAPI 3.0 specification that defines how files are stored and accessed on ant investor products
 *
 * API version: 1.0.0
 * Contact: info@antinvestor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"os"
)

type InlineObject struct {
	GroupId string `json:"group_id,omitempty"`

	SubscriptionId string `json:"subscription_id,omitempty"`

	Public bool `json:"public,omitempty"`

	Name string `json:"name,omitempty"`

	FileObject *os.File `json:"fileObject,omitempty"`
}
