/*
 * Ant Investor Files
 *
 * An openAPI 3.0 specification that defines how files are stored and accessed on ant investor products
 *
 * API version: 1.0.0
 * Contact: info@antinvestor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/files/",
		Index,
	},

	{
		"AddFile",
		strings.ToUpper("Post"),
		"/files/",
		AddFile,
	},

	{
		"DeleteFile",
		strings.ToUpper("Delete"),
		"/files/{id}",
		DeleteFile,
	},

	{
		"FindFileById",
		strings.ToUpper("Get"),
		"/files/{id}",
		FindFileById,
	},

	{
		"FindFiles",
		strings.ToUpper("Get"),
		"/files/",
		FindFiles,
	},
}
